export const catalogItems = [
  // Productos (5)
  {
    id: 1,
    type: "producto",
    title: "Plataforma de Monitoreo Inteligente",
    description: "Sistema con sensores IoT que permite el monitoreo en tiempo real de residuos. Mejora eficiencia, reduce costos y cumple regulaciones.",
    price: "$199/mes",
    image: "images/image1.jpg",
    imageAlt: "Plataforma de Monitoreo Inteligente",
  },
  {
    id: 2,
    type: "producto",
    title: "Sensores IoT para Gestión de Residuos",
    description: "Sensores inteligentes que miden nivel, tipo y temperatura en contenedores, optimizando la recolección.",
    price: "$120 por sensor",
    image: "images/image2.jpg",
    imageAlt: "Sensores IoT para Gestión de Residuos",
  },
  {
    id: 3,
    type: "producto",
    title: "Gateway de Comunicación IoT",
    description: "Dispositivo que centraliza la información de sensores y la transmite a la nube para análisis y control.",
    price: "$350 por unidad",
    image: "images/image3.jpg",
    imageAlt: "Gateway de Comunicación IoT",
  },
  {
    id: 4,
    type: "producto",
    title: "Aplicación Móvil para Ciudadanos",
    description: "App que fomenta participación ciudadana con gamificación y educación ambiental.",
    price: "Incluido en suscripción",
    image: "images/image4.jpg",
    imageAlt: "Aplicación Móvil para Ciudadanos",
  },
  {
    id: 5,
    type: "producto",
    title: "Módulo de Analítica Avanzada y Reportes Personalizados",
    description: "Dashboard con reportes detallados y métricas para toma de decisiones sustentables.",
    price: "Gratis en todos los planes",
    image: "images/image5.jpg",
    imageAlt: "Módulo de Analítica Avanzada y Reportes Personalizados",
  },

  // Servicios (5)
  {
    id: 6,
    type: "servicio",
    title: "Optimización de Rutas con IA",
    description: "Algoritmos inteligentes para rutas eficientes, ahorrando combustible y tiempo.",
    price: null,
    image: "images/image6.jpg",
    imageAlt: "Optimización de Rutas con IA",
  },
  {
    id: 7,
    type: "servicio",
    title: "Implementación y Personalización",
    description: "Configuración y capacitación para adaptar la plataforma a las necesidades del cliente.",
    price: "$5,000 - $20,000 único",
    image: "images/image7.jpg",
    imageAlt: "Implementación y Personalización",
  },
  {
    id: 8,
    type: "servicio",
    title: "Consultoría en Optimización de Gestión de Residuos",
    description: "Análisis y recomendaciones para mejorar procesos, reducir costos y cumplir normativas.",
    price: "$150 por hora",
    image: "images/image8.jpg",
    imageAlt: "Consultoría en Optimización de Gestión de Residuos",
  },
  {
    id: 9,
    type: "servicio",
    title: "Capacitación y Entrenamiento",
    description: "Cursos y talleres para maximizar el uso de la plataforma y promover buenas prácticas.",
    price: "$1,200 por sesión",
    image: "images/image9.jpg",
    imageAlt: "Capacitación y Entrenamiento",
  },
  {
    id: 10,
    type: "servicio",
    title: "Mantenimiento y Soporte Técnico Premium",
    description: "Soporte continuo, actualizaciones y atención rápida para garantizar funcionamiento óptimo.",
    price: "Planes mensuales o incluido en suscripción premium",
    image: "images/image10.jpg",
    imageAlt: "Mantenimiento y Soporte Técnico Premium",
  },
]
